packages:
  - apps/*
  - packages/*
catalog:
  "@babel/core": ^7.25.2
  "@babel/plugin-transform-react-jsx": ^7.27.1
  "@babel/preset-env": ^7.28.0
  "@babel/preset-react": ^7.27.1
  "@babel/preset-typescript": ^7.27.1
  "@better-auth/cli": 1.3.2
  "@better-auth/expo": 1.3.2
  "@better-auth/sso": ^1.3.2
  "@eslint/js": ^9.20.1
  "@expo/vector-icons": ^14.1.0
  "@hookform/resolvers": ^5.1.1
  "@next/eslint-plugin-next": ^15.1.7
  "@radix-ui/react-accordion": ^1.2.11
  "@radix-ui/react-alert-dialog": ^1.1.14
  "@radix-ui/react-aspect-ratio": ^1.1.7
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-checkbox": ^1.3.2
  "@radix-ui/react-collapsible": ^1.1.11
  "@radix-ui/react-context-menu": ^2.2.15
  "@radix-ui/react-dialog": ^1.1.14
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-hover-card": ^1.1.14
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-menubar": ^1.1.15
  "@radix-ui/react-navigation-menu": ^1.2.13
  "@radix-ui/react-popover": ^1.1.14
  "@radix-ui/react-progress": ^1.1.7
  "@radix-ui/react-radio-group": ^1.3.7
  "@radix-ui/react-scroll-area": ^1.2.9
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slider": ^1.3.5
  "@radix-ui/react-slot": ^1.1.2
  "@radix-ui/react-switch": ^1.2.5
  "@radix-ui/react-tabs": ^1.1.12
  "@radix-ui/react-toggle": ^1.1.9
  "@radix-ui/react-toggle-group": ^1.1.10
  "@radix-ui/react-tooltip": ^1.2.7
  "@react-native-community/datetimepicker": ^8.4.1
  "@react-native-picker/picker": ^2.11.0
  "@react-navigation/bottom-tabs": ^7.3.10
  "@react-navigation/elements": ^2.3.8
  "@react-navigation/native": ^7.1.6
  "@storybook/addon-a11y": ^9.0.17
  "@storybook/addon-docs": ^9.0.17
  "@storybook/addon-links": ^9.0.17
  "@storybook/nextjs": ^9.0.17
  "@storybook/react": ^9.0.17
  "@storybook/react-webpack5": ^9.0.17
  "@svgr/webpack": ^8.1.0
  "@t3-oss/env-nextjs": ^0.13.6
  "@tailwindcss/postcss": ^4.0.8
  "@tanstack/react-query": ^5.76.1
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@trpc/client": 11.1.2
  "@trpc/react-query": 11.1.2
  "@trpc/server": 11.1.2
  "@turbo/gen": ^2.4.2
  "@types/babel__core": ^7.20.5
  "@types/babel__preset-env": ^7.10.0
  "@types/jest": ^30.0.0
  "@types/node": ^20
  "@types/react": ~19.0.10
  "@types/react-dom": ^19
  "@typescript-eslint/eslint-plugin": ^8.37.0
  "@typescript-eslint/parser": ^8.37.0
  "@upstash/redis": ^1.35.1
  "@vercel/postgres": ^0.10.0
  babel-jest: ^30.0.4
  babel-loader: ^10.0.0
  better-auth: 1.3.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.1
  drizzle-zod: ^0.8.2
  embla-carousel-react: ^8.6.0
  eslint: ^9.25.0
  eslint-config-expo: ~9.2.0
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.5.5
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-turbo: ^2.4.2
  expo: ~53.0.9
  expo-blur: ~14.1.4
  expo-constants: ~17.1.6
  expo-dev-client: ^5.1.8
  expo-font: ~13.3.1
  expo-haptics: ~14.1.4
  expo-image: ~2.1.7
  expo-linking: ~7.1.5
  expo-router: ~5.0.6
  expo-secure-store: ^14.2.3
  expo-splash-screen: ~0.30.8
  expo-status-bar: ~2.2.3
  expo-symbols: ~0.4.4
  expo-system-ui: ~5.0.7
  expo-web-browser: ~14.1.6
  globals: ^15.15.0
  identity-obj-proxy: ^3.0.0
  input-otp: ^1.4.2
  jest: ^30.0.4
  jest-environment-jsdom: ^30.0.4
  lucide-react: ^0.475.0
  next: ^15.4.7
  next-themes: ^0.4.4
  postcss-loader: ^8.1.1
  postgres: ^3.4.5
  prettier: ^3.5.1
  react: 19.0.0
  react-day-picker: ^9.8.0
  react-dom: 19.0.0
  react-hook-form: ^7.60.0
  react-native: 0.79.2
  react-native-gesture-handler: ~2.24.0
  react-native-reanimated: ~3.17.4
  react-native-safe-area-context: 5.4.0
  react-native-screens: ~4.10.0
  react-native-web: ~0.20.0
  react-native-webview: 13.13.5
  react-resizable-panels: ^3.0.3
  recharts: 2.15.4
  sonner: ^2.0.6
  storybook: ^9.0.17
  superjson: 2.2.2
  tailwind-merge: ^3.0.1
  tailwindcss: ^4.0.8
  ts-jest: ^29.4.0
  turbo: ^2.4.2
  tw-animate-css: ^1.2.4
  typescript: 5.8.3
  typescript-eslint: ^8.37.0
  vaul: ^1.1.2
  zod: 3.25.5
